name: Trigger Semgrep Scan
env:
  SAST_EXCLUDE_LIST: 'services'
on:
  workflow_dispatch:  # This will allow you to manually trigger the workflow

jobs:
  sast:
    uses: clubpay/secureflow/.github/workflows/sast.yml@main
    
