name: Trigger SCA Scan
on:
  workflow_dispatch:  # This will allow you to manually trigger the workflow

jobs:
  sast:
    uses: clubpay/secureflow/.github/workflows/sast.yml@Test_Connection
      
    
