name: Trigger Secure Flow
on:
  workflow_dispatch:  # This will allow you to manually trigger the workflow

jobs:
  sast:
    uses: clubpay/secureflow/.github/workflows/sast.yml@Authenticate_to_Teleport
    secrets: inherit
  sca:
    uses: clubpay/secureflow/.github/workflows/sca.yml@Authenticate_to_Teleport
    secrets: inherit

      
    
